### ISSUE TITLE
Alignment and Footer

### ISSUE THREAD

**Issue by mato0039** [mato0039/saas-website#2]
Hi Christina, 

I was wondering why my input fields are not centered on the Sign Up, Sign In and Homepage? I tried to use **text-center** in the surrounding **div** but that didn't seem to work. 

Also my footer **ul's** are not adhering to the grid I've assigned them in the medium and large screen sizes. 

Any chance you could help?

Thanks!

Cathy

@muxlowc

**Comment by muxlowc** [comment]
@mato0039 

1) to align your input fields, try using the class "center-content" on your form - that should center align it!

2) You will need to change your gridifier settings - you currently are using the default settings which is for 4 columns (ie. your currently gridifier doesn't know that l-1-5 exits), so you'll just need to set your column numbers to 5 :)

**Comment by mato0039** [comment]
Oh that makes sense! Thanks a lot!!!!!
