### ISSUE TITLE
Grid Issues

### ISSUE THREAD

**Issue by mato0039** [mato0039/saas-website#3]
Hi Christina, 

I'm trying to center my cards but when I do, they change shape. I used the **center-content** class to center them within the **div** but they changed shape. 

I put a max-width on them so they could stay on the same line, prior to that, the third card would bump down. Not sure if this is the cause? 

Anyway, I've added screenshots so you can see what I mean. 

<img width="1627" alt="Screen Shot 2020-04-13 at 10 07 59 AM" src="https://user-images.githubusercontent.com/55108737/79127031-14add580-7d6f-11ea-8988-c4903e076ac6.png">
<img width="1657" alt="Screen Shot 2020-04-13 at 10 08 23 AM" src="https://user-images.githubusercontent.com/55108737/79127045-1d061080-7d6f-11ea-8ea6-3039c694cb76.png">

@muxlowc

**Comment by mato0039** [comment]
Ok....I fixed it. It had to do with my text sizes? I made my body copy smaller and that seemed to help.... 🤷🏾‍♀️

**BUT**

Since I'm here, is it necessary to have a **Home** button if you can just click on the **logo** to get to the home page? 

@muxlowc

**Comment by muxlowc** [comment]
@mato0039  Have you tried using content-distribute as well? [https://learn-the-web.algonquindesign.ca/topics/gridifier-cheat-sheet/#example-solutions]

using the logo as your home link is fine!

**Comment by mato0039** [comment]
Ok great! Thanks a lot :)
