### ISSUE TITLE
Alignment 

### ISSUE THREAD

**Issue by mato0039** [mato0039/saas-website#4]
Hi Christina, 

How do I put the input and button on one line? I tried using a grid but the button stays stuck on the second line. In modulifier, **.btn** has **inline-block** on it so technically it should be able to adhere to the grid right? Not sure. 

<img width="842" alt="Screen Shot 2020-04-13 at 5 24 47 PM" src="https://user-images.githubusercontent.com/55108737/79162871-003bfe00-7dac-11ea-81da-b4076b06656e.png">

@muxlowc

**Comment by muxlowc** [comment]
```
        <form class="push" action="index.html" method="post">
          <div class="grid grid-middle center-content">
            <div class="unit unit-1-2 inline gutter">
              <label for="email"></label>
              <input id="email" type="email" placeholder="Enter your email" name="email">
            </div>
            <div class="unit unit-1-2 text-center right inline">
              <button class="btn" type="submit">Sign Up</button>
            </div>
```

1) you should have your button inside of your form tag
2) i added in the grid again, and it worked? and I added center-content on the grid div (this class has some weird properties with flex-wrap or something, so I think if this class is in the wrong spot, it doesnt work well haha)

hope that helps!
@mato0039

**Comment by mato0039** [comment]
I'm on it! That helps a lot Christina, thanks :) 

Does this count for the Saas check-in? 

@muxlowc

**Comment by muxlowc** [comment]
@mato0039 Yep! thanks!

**Comment by mato0039** [comment]
Thank you it worked :)
