### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by mato0039** [mato0039/saas-website#5]
Hi Christina, 

How do I center align the header and h2 on mobile view? 

@muxlowc

<img width="426" alt="Screen Shot 2020-04-13 at 5 29 14 PM" src="https://user-images.githubusercontent.com/55108737/79163195-95d78d80-7dac-11ea-8832-a560db3c8243.png">

**Comment by muxlowc** [comment]
@mato0039 

Okay, so you'll have to have your header/h2 left aligned to start in your css (NOT by using classes in your html) for example:

header, 
h2 {
  text-align: center;
}

Then You tag your header and h2 in the larger media query (maybe tablet size?)

@media only screen and (min-width: 38em) {
  h2 {
  text-align: left;
}

**Comment by mato0039** [comment]
This was helpful! Thank you!!!
